echo Stopping Overpass Diff service...
systemctl stop overpass-diff

echo Stopping Overpass Main service...
systemctl stop overpass.service

echo Removing file locks...
rm -f /dev/shm/osm3s_v0.7.54_osm_base
rm -f db/osm3s_v0.7.54_osm_base

echo Deleting old DB copy...
rm -rf db-copy

echo Copying existing DB files...
cp -arv db db-copy

echo Deleting existing DB files...
rm -rf db
mkdir db

echo Cloning the Overpass DB...
osm-3s_v0.7.54/bin/download_clone.sh --db-dir=db --source=http://dev.overpass-api.de/api_drolbr/ --meta=no

echo Setting up user rights to the new DB files...
chmod -R 755 db

echo Starting Overpass Main service...
systemctl start overpass.service

echo Starting Overpass Diff service...
systemctl start overpass-diff
